### PR TITLE
Fixed on hover text for Obtanium and Quark's icons

### PR DESCRIPTION
**Pull request by gandi800**
First time publicly contributing on GitHub let me know if I did something wrong with the pull request or commit.

### CODE REVIEW

**Comment by q00u** [comment]
What does this do? I couldn't see a change on firefox

**Comment by gandi800** [comment]
In Chrome when you hover over the icons for Obtanium and Quark's there is
no hover text.

**Comment by q00u** [comment]
I'm seeing hovertext in latest chrome. Are you running latest synergism?

**Comment by 4444N** [comment]
This changes nothing to the effect of what the title says. There is already title text for both of these in both Kongregate and GitHub release.

**Comment by gandi800** [comment]
You're absolutely right. I swear when I was initially playing on Kongregate
the hover text wasn't working. Sorry to have made you investigate something
that wasn't real. I'll make sure to test better in the future.

Cheers

**Pull request closed without merging**
